---
#------------------------------------------------------------------------------
# Install Nginx
#------------------------------------------------------------------------------
- name: Make sure nginx installed
  tags: nginx_install
  package: name=nginx state=present

#------------------------------------------------------------------------------
# Content
#------------------------------------------------------------------------------
- import_tasks: index.yml
  tags: nginx_index

#------------------------------------------------------------------------------
# Config Nginx
#------------------------------------------------------------------------------
- import_tasks: config.yml
  tags: nginx_config

#------------------------------------------------------------------------------
# Nginx Static Resources
#------------------------------------------------------------------------------
- import_tasks: static.yml
  tags: nginx_static

#------------------------------------------------------------------------------
# Restart Nginx
#------------------------------------------------------------------------------
- import_tasks: restart.yml
  when: nginx_enabled|bool
  tags: nginx_restart

#------------------------------------------------------------------------------
# Nginx Exporter
#------------------------------------------------------------------------------
- import_tasks: exporter.yml
  when: nginx_enabled|bool
  tags: nginx_exporter

...