---
#------------------------------------------------------------------------------
# setup pigsty local docs (/www/docs -> http://pigsty/docs)
#------------------------------------------------------------------------------
- name: Setup docs if exists
  tags: nginx_doc
  ignore_errors: true     # skip if pev2 not available on repo
  shell: |
    # /www/pigsty/docs.tgz is the default path
    DOCS_TARBALL="{{ nginx_home }}/{{ repo_name }}/docs.tgz"
    
    # skip if docs packages not available
    if [[ ! -f ${DOCS_TARBALL} ]]; then
        exit 0;
    fi
    
    rm -rf /{{ nginx_home }}/docs
    tar -xf ${DOCS_TARBALL} -C {{ nginx_home }}

#------------------------------------------------------------------------------
# setup pev2 explain visualizer
#------------------------------------------------------------------------------
- name: Setup pev2 if exists
  tags: nginx_pev2
  ignore_errors: true     # skip if pev2 not available on repo
  shell: |
    # /www/pigsty/pev2.tar.gz is the default path
    PEV2_TARBALL="{{ nginx_home }}/{{ repo_name }}/pev2.tar.gz"
    
    # skip if pev2 packages not available
    if [[ ! -f ${PEV2_TARBALL} ]]; then
        exit 0;
    fi
    
    rm -rf /{{ nginx_home }}/pev2
    tar -xf ${PEV2_TARBALL} -C {{ nginx_home }}

...