version: "3"
services:
  bytebase:
    container_name: bytebase
    image: bytebase/bytebase:1.0.5
    restart: unless-stopped
    ports:
      - "8887:8887"
    command: |
      --host http://ddl.pigsty --port 8887 --data /var/opt/bytebase