#!/usr/bin/env ansible-playbook
---
#==============================================================#
# File      :   nodes-remove.yml
# Mtime     :   2022-02-22
# Mtime     :   2022-03-20
# Desc      :   remove nodes from pigsty
# Path      :   nodes-remove.yml
# Copyright (C) 2018-2022 Ruohang Feng (rh@vonng.com)
#==============================================================#

#---------------------------------------------------------------
# DeRegister
#---------------------------------------------------------------
- name: Register Remove
  become: yes
  hosts: all
  gather_facts: no
  tags: register
  tasks:

    #---------------------------------------------
    # Deregister from prometheus
    #---------------------------------------------
    - name: Remove node target from prometheus
      tags: register_prometheus
      become: yes
      ignore_errors: yes
      delegate_to: '{{ item }}'
      with_items: '{{ groups["meta"] }}'
      file: state=absent path=/etc/prometheus/targets/nodes/{{ inventory_hostname }}.yml

    #---------------------------------------------
    # Deregister from consul if applicable
    #---------------------------------------------
    - name: Remove node_exporter service from consul
      tags: register_consul
      when: dcs_registry == 'consul'
      file:
        path: /etc/consul.d/svc-node-exporter.json
        state: absent

    - name: Reload consul to dereigster node_exporter
      tags: register_consul
      when: dcs_registry == 'consul'
      systemd: name=consul state=reloaded

    #---------------------------------------------
    # Other Deregister Logic
    #---------------------------------------------



#------------------------------------------------------------------------------
# Remove Node Exporter
#------------------------------------------------------------------------------
- name: Node Exporter Remove
  become: yes
  hosts: all
  gather_facts: no
  tags: node-exporter
  ignore_errors: yes
  tasks:
    - name: Stop and disable node_exporter service
      systemd: name=node_exporter state=stopped enabled=no daemon_reload=yes

#------------------------------------------------------------------------------
# Remove Promtail
#------------------------------------------------------------------------------
- name: Promtail Agent Remove
  become: yes
  hosts: all
  gather_facts: no
  tags: promtail
  ignore_errors: yes
  tasks:
    - name: Stop and disable promtail service
      systemd: name=promtail state=stopped enabled=no daemon_reload=yes
      # when: promtail_enabled|bool


#---------------------------------------------------------------
# Docker
#---------------------------------------------------------------
- name: Docker Remove
  become: yes
  hosts: all
  gather_facts: no
  tags: docker
  ignore_errors: yes
  tasks:
    - name: Stop and disable docker service
      systemd: name=docker state=stopped enabled=no daemon_reload=yes
      # when: docker_enabled|bool


#---------------------------------------------------------------
# Remove DCS:Consul
#---------------------------------------------------------------
# force remove with ./nodes-remove.yml -t consul -e consul_safeguard=false
- name: DCS Remove
  become: yes
  hosts: all
  gather_facts: no
  tags: dcs
  tasks:

    #------------------------------------------------------------------------------
    # Remove Consul
    #------------------------------------------------------------------------------
    - name: Remove DCS Consul
      tags: consul
      when: dcs_registry == 'consul'
      become: yes
      block:

        - name: Abort due to consul_safeguard enabled
          connection: local
          when: consul_safeguard|bool
          any_errors_fatal: true
          fail: msg="Abort due to consul_safeguard for {{ inventory_hostname }} is enabled, use -e consul_safeguard=false to override"

        - name: Consul leave cluster
          ignore_errors: yes
          command: consul leave

        - name: Stop and disable consul
          ignore_errors: yes
          systemd: name=consul state=stopped enabled=no daemon_reload=yes

        - name: Remove consul config and data
          ignore_errors: yes
          file: path={{ item }} state=absent
          with_items:
            - /etc/consul.d
            - "{{ consul_data_dir }}"


...