#!/usr/bin/env ansible-playbook
---
#==============================================================#
# File      :   pgsql-remove.yml
# Mtime     :   2020-05-12
# Mtime     :   2022-02-23
# Desc      :   remove pgsql from nodes
# Path      :   pgsql-remove.yml
# Copyright (C) 2018-2022 Ruohang Feng (rh@vonng.com)
#==============================================================#


#==============================================================#
# Playbook : Remove pgsql Cluster/Instance                     #
#==============================================================#
#  Remove cluster `pg-test`
#     pgsql-remove.yml -l pg-test
#
#  Remove instance (10.10.10.13) among cluster `pg-test`
#     pgsql-remove.yml -l 10.10.10.13
#
#  Remove postgres data along with pg_packages
#     pgsql-remove.yml -e rm_pgdata=true -e rm_pgpkgs=true
#
#  Register cluster/instance to infrastructure
#     pgsql-remove.yml --tags=register  # prometheus, grafana, nginx
#     pgsql-remove.yml --tags=service   # haproxy, vip
#     pgsql-remove.yml --tags=monitor   # pg_exporter, pgbouncer_exporter, node_exporter, promtail
#     pgsql-remove.yml --tags=pgbouncer # pgbouncer
#     pgsql-remove.yml --tags=postgres  # postgres
#     pgsql-remove.yml --tags=haproxy   # remove haproxy
#==============================================================#


#------------------------------------------------------------------------------
# Honor pg_safeguard
#------------------------------------------------------------------------------
- name: PGSQL Remove Precheck
  hosts: all
  tags: precheck
  gather_facts: no
  tasks:

    - name: Abort due to pg_safeguard enabled
      connection: local
      when: pg_safeguard|bool
      any_errors_fatal: true
      fail: msg="Abort due to pg_safeguard for {{ pg_cluster }}-{{ pg_seq }} @ {{ inventory_hostname }} is enabled, use -e pg_safeguard=false to override"

#------------------------------------------------------------------------------
# Remove PGSQL from nodes
#------------------------------------------------------------------------------
- name: PGSQL Remove
  become: yes
  hosts: all
  tags: pg-remove
  gather_facts: no
  ignore_errors: yes
  vars:

    rm_pgdata: false        # remove postgres data? false by default
    rm_pgpkgs: false        # uninstall pg_packages? false by default

  roles:

    # remove pgsql cluster without safeguard
    - role: pg_remove
      when: not pg_safeguard|bool

...