#!/usr/bin/env ansible-playbook
---
#==============================================================#
# File      :   pigsty-matrixdb.yml
# Ctime     :   2022-01-19
# Mtime     :   2022-03-22
# Desc      :   init matrixdb with postgres roles
# Path      :   pigsty-matrixdb.yml
# Copyright (C) 2018-2022 Ruohang Feng (rh@vonng.com)
#==============================================================#

#---------------------------------------------------------------
# How to create greenplum/matrixdb cluster ?
#  1. infra.yml         # install pigsty meta node
#  2. nodes.yml         # init nodes for greenplum
#  3. pigsty-matrixdb.yml  # init matrixdb on nodes
#  4. finish with install ui @ http://10.10.10.10:8240
#---------------------------------------------------------------

#---------------------------------------------------------------
- name: Check Inventory
  hosts: all
  gather_facts: no
  tags: preflight
  tasks:
    - name: Check greenplum inventory
      assert:
        that:
          - nodename is defined    # you have to explict set hostname for gp members
          - gp_role is defined and (gp_role == 'master' or gp_role == 'segment')
          - gp_role == 'master' or (gp_role == 'segment' and pg_instances is defined and pg_instances|length > 0)

#---------------------------------------------------------------
# init greenplum/matrixdb master cluster
#---------------------------------------------------------------
- name: GPSQL Init
  become: yes
  hosts: all
  gather_facts: no
  tags: gp-init
  vars:
    pg_dbsu: mxadmin              # matrixdb dbsu
    pg_dbsu_uid: 1226             # matrixdb dbsu uid & gid
    pg_dbsu_home: /home/mxadmin   # matrixdb dbsu homedir
    patroni_enabled: false        # do not pull up normal postgres with patroni
    pg_provision: false           # provision postgres template & database & user
    haproxy_enabled: false        # disable haproxy monitor on greenplum
    pg_packages: [ 'matrixdb postgresql${pg_version}* pgbouncer pg_exporter node_exporter consul pgbadger pg_activity' ]
    pg_extensions: [ ]
  roles:
    - role: postgres

#---------------------------------------------------------------
# init greenplum/matrixdb master monitor
#---------------------------------------------------------------
- name: GPSQL Monitor
  become: yes
  hosts: all
  gather_facts: no
  tags: gp-monitor
  vars:
    pg_dbsu: mxadmin                          # matrixdb dbsu
    haproxy_enabled: false                    # disable haproxy monitor on greenplum
    pg_exporter_exclude_database: 'template0,template1,postgres,matrixmgr' # optional, comma separated list of database that WILL NOT be monitored when auto-discovery enabled

  roles:

    # gp master / standby cluster are treated as common pg cluster
    - role: pg_exporter
      tags: gp-master-monitor
      when: gp_role == 'master'

    # multiple instance monitoring on gp segment nodes
    - role: pg_exporters
      tags: gp-segment-monitor
      when: gp_role == 'segment'



#---------------------------------------------------------------
# print matrixdb password for web ui installer
#---------------------------------------------------------------
- name: GPSQL Password
  become: yes
  hosts: all
  gather_facts: no
  tags: gp-pass
  tasks:
    - name: Fetch matrixdb password
      when: gp_role == 'master'
      shell: /bin/cat /etc/matrixdb/auth.conf | grep -Eo 'Password = "(.*)"' | grep -Eo '"(.*)"'
      register: matrixdb_auth_credential

    - name: 'Visit http://mx.pigsty with password:'
      when: gp_role == 'master'
      debug: msg={{ matrixdb_auth_credential.stdout | replace('"', '' ) }}


