---
#------------------------------------------------------------------------------
# Install
#------------------------------------------------------------------------------
- name: Install promtail via yum
  tags: promtail_install
  when: promtail_enabled|bool
  package: name=promtail state=present

#------------------------------------------------------------------------------
# Cleanup
#------------------------------------------------------------------------------
- name: Cleanup promtail positions
  tags: promtail_clean
  when: promtail_enabled|bool and promtail_clean|bool
  file: path={{ promtail_positions }} state=absent

#------------------------------------------------------------------------------
# Config
#------------------------------------------------------------------------------
- name: Config promtail
  tags: promtail_config
  when: promtail_enabled|bool
  block:
    - name: Copy promtail systemd service
      copy: src=promtail.service dest=/usr/lib/systemd/system/promtail.service

    # use hostname as nodename if not provided
    - name: Fetch hostname from server if no node name is given
      when: nodename is not defined or nodename == ''
      shell: echo $HOSTNAME
      register: hostname_result

    - name: Setup nodename according to hostname
      when: nodename is not defined or nodename == ''
      set_fact:
        nodename: "{{ hostname_result.stdout }}"

    - name: Render promtail main config
      template: src=promtail.yml.j2 dest=/etc/promtail.yml

    - name: Render promtail default config
      copy:
        dest: /etc/default/promtail
        owner: root
        content: |
          PROMTAIL_OPTS='{{ promtail_options }}'
          PROMTAIL_POSITIONS={{ promtail_positions }}
          PROMTAIL_SEND_URL='{{ loki_endpoint }}'

#------------------------------------------------------------------------------
# Launch
#------------------------------------------------------------------------------
- name: Launch promtail
  tags: promtail_launch
  when: promtail_enabled|bool
  block:
    - name: Launch promtail
      systemd: name=promtail state=restarted enabled=yes daemon_reload=yes

    - name: Wait for promtail online
      wait_for: host=127.0.0.1 port={{ promtail_port }} state=started timeout=20

...