version: "3"
services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pigsty.cc
      PGADMIN_DEFAULT_PASSWORD: pigsty
    ports:
      - "8885:80"