---
#--------------------------------------------------------------#
# Create Directories
#--------------------------------------------------------------#
- name: Create pigsty directories
  become: yes
  tags: environ_dirs
  block:

    - name: Create pigsty resource dirs on /etc/pigsty
      file: path={{ item }} state=directory owner=root
      with_items:
        - /etc/pigsty
        - /etc/pigsty/playbooks
        - /etc/pigsty/dashboards
        - /etc/pigsty/datasources


#--------------------------------------------------------------#
# Allow meta admin initiate patronictl commands
#--------------------------------------------------------------#
- name: Create patronictl resource
  become: yes
  tags: environ_patronictl
  template:
    dest: /etc/pigsty/patronictl.yml
    mode: 0644
    src: patronictl.yml.j2


#--------------------------------------------------------------#
# Make sure ssh credential exists (id_rsa.pub)
#--------------------------------------------------------------#
- name: Guarentee admin ssh crendential exists
  become: no
  ignore_errors: true
  tags: environ_ssh
  block:
    - name: Get current username
      command: whoami
      changed_when: false
      register: remote_username

    - name: Create admin user ssh key pair if not exists
      user:
        name: "{{ remote_username.stdout }}"
        generate_ssh_key: yes


#--------------------------------------------------------------#
# Setup pgpass & pg_service
#--------------------------------------------------------------#
- name: Setup postgres pass and service
  become: no
  tags: environ_pgpass
  ignore_errors: true
  block:
    - name: Write default user credential to pgpass
      lineinfile: dest=~/.pgpass state=present create=yes mode=0600 line={{ item }}
      with_items:
        - "*:*:*:{{ pg_replication_username }}:{{ pg_replication_password }}"
        - "*:*:*:{{ pg_monitor_username }}:{{ pg_monitor_password }}"
        - "*:*:*:{{ pg_admin_username }}:{{ pg_admin_password }}"

    - name: Write default meta service to pg_service
      tags: pgsvc
      template:
        dest: ~/.pg_service.conf
        mode: '0600'
        src: pg_service.conf.j2

    - name: Write servers.json to home dir
      tags: pgserver
      template:
        dest: ~/.servers.json
        mode: '0600'
        src: servers.j2
      vars:
        servers_query: '[@.*][0][?pg_cluster && pg_cluster!=""].{pg_cluster: pg_cluster,pg_seq: pg_seq,pg_port: pg_port,pg_host: inventory_hostname,pg_admin_username:pg_admin_username,pg_admin_password: pg_admin_password}'


#--------------------------------------------------------------#
# Setup envrion_vars
#--------------------------------------------------------------#
- name: Setup postgres pass and service
  become: no
  tags: environ_vars
  ignore_errors: true
  block:

    # create ~/.pigsty bash file
    - name: Set environment for admin user
      template:
        dest: ~/.pigsty
        mode: 0700
        src: pigsty.j2

    # load ~/.pigsty in ~/.bashrc
    - name: Enable environment for admin user
      lineinfile:
        dest: ~/.bashrc
        state: present
        create: yes
        mode: 0644
        line: '[ -f ~/.pigsty ] && . ~/.pigsty'


#--------------------------------------------------------------#
# Setup cmdb
#--------------------------------------------------------------#
# TODO: cmdb init

...