---
#------------------------------------------------------------------------------
# register infra service to consul
#------------------------------------------------------------------------------
- name: Register infra service to consul
  tags: [ infra_register, register_consul ]
  when: dcs_registry == 'consul'
  ignore_errors: true
  block:

    - name: Register nginx service to consul
      when: nginx_enabled|bool
      template: src=svc-nginx.json.j2 dest=/etc/consul.d/svc-nginx.json owner=consul mode=0660

    - name: Register nginx-exporter service to consul
      when: nginx_enabled|bool
      template: src=svc-nginx-exporter.json.j2 dest=/etc/consul.d/svc-nginx-exporter.json owner=consul mode=0660

    - name: Register prometheus service to consul
      when: prometheus_enabled|bool
      template: src=svc-prometheus.json.j2 dest=/etc/consul.d/svc-prometheus.json owner=consul mode=0660

    - name: Register alertmanager service to consul
      when: prometheus_enabled|bool
      template: src=svc-alertmanager.json.j2 dest=/etc/consul.d/svc-alertmanager.json owner=consul mode=0660

    - name: Register grafana service to consul
      when: grafana_enabled|bool
      template: src=svc-grafana.json.j2 dest=/etc/consul.d/svc-grafana.json owner=consul mode=0660

    - name: Register loki service to consul
      when: loki_enabled|bool
      template: src=svc-loki.json.j2 dest=/etc/consul.d/svc-loki.json owner=consul mode=0660

    - name: Register dnsmasq service to consul
      when: nameserver_enabled|bool
      template: src=svc-dnsmasq.json.j2 dest=/etc/consul.d/svc-dnsmasq.json owner=consul mode=0660

    - name: Reload consul
      systemd: name=consul state=reloaded enabled=yes daemon_reload=yes


#--------------------------------------------------------------#
# Register infra service to prometheus
#--------------------------------------------------------------#
- name: Render infra file-sd targets targets for prometheus
  tags: [ infra_register, register_prometheus ]
  ignore_errors: true
  delegate_to: '{{ item }}'
  with_items: '{{ groups["meta"] }}'
  template: src=infra.yml.j2 dest=/etc/prometheus/targets/infra/{{ inventory_hostname}}.yml owner=prometheus mode=0644

...