---
#-----------------------------------------------------------------
# NODE_IDENTITY
#-----------------------------------------------------------------
meta_node: false                  # node with meta_node flag will be marked as admin node
# nodename:          # [OPTIONAL] # node instance identity, used as `ins`, hostname by default
node_cluster: nodes  # [OPTIONAL] # node cluster identity, used as `cls`, 'nodes' by default
nodename_overwrite: true          # overwrite node's hostname with nodename?
nodename_exchange: false          # exchange nodename among play hosts?

#-----------------------------------------------------------------
# NODE_DNS
#-----------------------------------------------------------------
node_etc_hosts_default:           # static dns records in /etc/hosts
  - 10.10.10.10 meta pigsty c.pigsty g.pigsty l.pigsty p.pigsty a.pigsty api.pigsty adm.pigsty cli.pigsty ddl.pigsty lab.pigsty
node_etc_hosts: []                # extra static dns records in /etc/hosts
node_dns_method: none             # add (default) | none (skip) | overwrite (remove old settings)
node_dns_servers: [ ]                # dynamic nameserver in /etc/resolv.conf
node_dns_options:                 # dns resolv options
  - options single-request-reopen timeout:1 rotate
  - domain service.consul

#-----------------------------------------------------------------
# NODE_REPO
#-----------------------------------------------------------------
node_repo_method: local           # none|local: ad local repo|public: add upstream directly
node_repo_remove: true            # remove existing repo on nodes?
node_repo_local_urls:             # list local repo url, if node_repo_method = local
  - http://pigsty/pigsty.repo

node_packages: [ ]                # extra packages for all nodes
node_packages_default:            # common packages for all nodes
  - wget,sshpass,ntp,chrony,tuned,uuid,lz4,make,patch,bash,lsof,wget,unzip,git,ftp,vim-minimal,ca-certificates
  - numactl,grubby,sysstat,dstat,iotop,bind-utils,net-tools,tcpdump,socat,ipvsadm,telnet,tuned,nc,pv,jq,perf
  - readline,zlib,openssl,openssl-libs,openssh-clients,python3,python36-requests,node_exporter,consul,etcd,promtail
node_packages_meta:               # extra packages for meta nodes
  - grafana,prometheus2,alertmanager,loki,nginx_exporter,blackbox_exporter,pushgateway,redis,postgresql14
  - nginx,ansible,pgbadger,python-psycopg2,dnsmasq,coreutils,diffutils,polysh,docker-ce,docker-compose
node_packages_meta_pip: jupyterlab

#-----------------------------------------------------------------
# NODE_TUNE
#-----------------------------------------------------------------
node_disable_firewall: true       # disable firewall
node_disable_selinux: true        # disable selinux
node_disable_numa: false          # disable numa (node reboot required)
node_disable_swap: false          # disable swap, use with caution
node_static_network: true         # keep dns resolver settings after reboot
node_disk_prefetch: false         # setup disk prefetch on HDD to increase performance
node_kernel_modules: [ softdog, br_netfilter, ip_vs, ip_vs_rr, ip_vs_rr, ip_vs_wrr, ip_vs_sh ]
node_tune: tiny                   # install and activate tuned profile: none|oltp|olap|crit|tiny
node_sysctl_params: { }           # set additional sysctl parameters, k:v format

#-----------------------------------------------------------------
# NODE ADMIN
#-----------------------------------------------------------------
node_data_dir: /data              # main data directory
node_admin_enabled: true          # create a default admin user defined by `node_admin_*` ?
node_admin_uid: 88                # uid and gid for this admin user
node_admin_username: dba          # name of this admin user, dba by default
node_admin_ssh_exchange: true     # exchange admin ssh key among each pgsql cluster ?
node_admin_pk_current: true       # add current user's ~/.ssh/id_rsa.pub to admin authorized_keys ?
node_admin_pk_list: [ ]           # ssh public keys to be added to admin user (REPLACE WITH YOURS!)

#-----------------------------------------------------------------
# NODE_TIME
#-----------------------------------------------------------------
node_timezone: Asia/Hong_Kong     # default node timezone, empty will not change
node_ntp_enabled: true            # enable ntp service? false will leave ntp service untouched
node_ntp_service: ntp             # ntp service provider: ntp|chrony
node_ntp_servers:                 # default NTP servers
  - pool pool.ntp.org iburst
node_crontab_overwrite: true      # true will overwrite /etc/crontab, false will append crontab
node_crontab: [ ]                 # crontab entries in /etc/crontab

#-----------------------------------------------------------------
# REPO (Reference)
#-----------------------------------------------------------------
repo_upstreams: []
...
