---
#-----------------------------------------------------------------
# REDIS_REMOVE
#-----------------------------------------------------------------
redis_uninstall: false            # uninstall redis & redis_exporter? false by default

#-----------------------------------------------------------------
# REDIS (REFERENCE)
#-----------------------------------------------------------------
redis_fs_main: /data              # main fs mountpoint for redis data
redis_safeguard: false            # prevent purging running redis instance?
redis_clean: true                 # purging existing redis during initialization?
...