---
#------------------------------------------------------------------------------
# Dnsmasq
#------------------------------------------------------------------------------
- name: Setup dnsmasq service
  tags: nameserver
  block:

    # - install - #
    - name: Make sure dnsmasq package installed
      package: name=dnsmasq state=present

    # - config - #
    - name: Copy dnsmasq /etc/dnsmasq.d/config
      template: src=dnsmasq.conf.j2 dest=/etc/dnsmasq.d/config

    # - record - #
    - name: Add dynamic dns records to meta
      lineinfile: path=/etc/hosts line="{{ item }}"
      with_items: "{{ dns_records }}"

    # - launch - #
    - name: Launch meta dnsmasq service
      when: nameserver_enabled|bool
      systemd: name=dnsmasq state=restarted enabled=yes daemon_reload=yes

    # - wait - #
    - name: Wait for meta dnsmasq online
      when: nameserver_enabled|bool
      wait_for: host=localhost port=53 state=started

...