---
#-----------------------------------------------------------------
# LOKI
#-----------------------------------------------------------------
loki_enabled: true                # enable loki? only works on meta nodes
loki_clean: false                 # whether remove existing loki data
loki_endpoint: http://10.10.10.10:3100/loki/api/v1/push # where to push data
loki_options: '-config.file=/etc/loki.yml -config.expand-env=true'
loki_data_dir: /data/loki         # default loki data dir
loki_retention: 15d               # log retention period
...