#------------------------------------------------------------------------------
# Install
#------------------------------------------------------------------------------
- name: Install loki via yum
  tags: loki_install
  package: name=loki state=present

#------------------------------------------------------------------------------
# Cleanup
#------------------------------------------------------------------------------
- name: Cleanup loki
  tags: loki_clean
  when: loki_clean|bool
  file: path={{ loki_data_dir }} state=absent owner=prometheus

#------------------------------------------------------------------------------
# Config
#------------------------------------------------------------------------------
- name: Config loki
  tags: loki_config
  block:

    - name: Make sure loki data & rule dir exists
      file: path={{ loki_data_dir }}/data/rules/fake state=directory owner=prometheus

    - name: Copy loki systemd service
      copy: src=loki.service dest=/usr/lib/systemd/system/loki.service

    - name: Templating loki.yml main config
      template: src=loki.yml dest=/etc/loki.yml owner=prometheus

    - name: Render loki default config
      copy:
        dest: /etc/default/loki
        owner: prometheus
        content: |
          LOKI_OPTS='{{ loki_options }}'
          LOKI_DATA={{ loki_data_dir }}
          LOKI_RETENTION_PERIOD={{ loki_retention }}


#------------------------------------------------------------------------------
# Launch
#------------------------------------------------------------------------------
- name: Launch loki
  tags: loki_launch
  when: loki_enabled|bool
  block:
    - name: Launch Loki
      systemd: name=loki state=restarted enabled=yes daemon_reload=yes

    - name: Wait for loki online
      wait_for: host=127.0.0.1 port=3100 state=started timeout=20

...
