---
#--------------------------------------------------------------#
# Remove PG Exporter                               [pg_exporter]
#--------------------------------------------------------------#
- name: remove postgres exporter
  tags: pg_exporter
  become: yes
  ignore_errors: yes
  block:

    - name: stop and disable pg_exporter service
      systemd: name=pg_exporter state=stopped enabled=no daemon_reload=yes

    - name: remove pg_exporter config file
      file: name=/etc/default/pg_exporter state=absent

#--------------------------------------------------------------#
# Remove Pgbouncer Exporter                 [pgbouncer_exporter]
#--------------------------------------------------------------#
- name: remove pgbouncer exporter
  tags: pgbouncer_exporter
  become: yes
  ignore_errors: yes
  block:

    - name: stop and disable pgbouncer_exporter service
      systemd: name=pgbouncer_exporter state=stopped enabled=no daemon_reload=yes

    - name: remove pgbouncer_exporter config file
      file: name=/etc/default/pgbouncer_exporter state=absent

...