---
#------------------------------------------------------------------------------
# Remove Pgbouncer
#------------------------------------------------------------------------------
- name: Remove Pgbouncer
  become: yes
  ignore_errors: yes
  block:

    #---------------------------------------------
    # Deregister Service
    #---------------------------------------------
    - name: Remove pgbouncer service from consul
      tags: consul_registry
      when: dcs_registry == 'consul'
      file:
        path: /etc/consul.d/svc-pgbouncer.json
        state: absent

    - name: Reload consul to dereigster pgbouncer
      when: dcs_registry == 'consul'
      systemd: name=consul state=reloaded


    #---------------------------------------------
    # Stop Service
    #---------------------------------------------
    - name: Stop and disable pgbouncer service
      systemd: name=pgbouncer state=stopped enabled=no daemon_reload=yes
...