---
#------------------------------------------------------------------------------
# Remove HAProxy Service Provider
#------------------------------------------------------------------------------
- name: Remove haproxy service provider
  tags: haproxy
  become: yes
  ignore_errors: yes
  # when: haproxy_enabled|bool
  block:

    - name: Remove cluster service from consul
      tags: consul_registry
      when: dcs_registry == 'consul'
      file:
        path: /etc/consul.d/svc-{{ pg_cluster }}-{{ service.name }}.json
        state: absent
      vars:
        service: "{{ item }}"
      with_items: "{{ pg_services + pg_services_extra }}"

    - name: Remove haproxy service from consul
      tags: consul_registry
      when: dcs_registry == 'consul'
      file:
        path: /etc/consul.d/svc-haproxy.json
        state: absent

    - name: Reload consul to dereigster haproxy
      when: dcs_registry == 'consul'
      systemd: name=consul state=reloaded

    - name: Stop and disable haproxy load balancer
      systemd: name=haproxy state=stopped enabled=no daemon_reload=yes


#------------------------------------------------------------------------------
# Remove VIP-Manager
#------------------------------------------------------------------------------
# TODO: if you have external vip service provider, remove it here
- name: Stop and disable vip-manager
  tags: vip
  become: yes
  ignore_errors: yes
  systemd: name=vip-manager state=stopped enabled=no daemon_reload=yes


...