---
#-----------------------------------------------------------------
# REPO
#-----------------------------------------------------------------
repo_name: pigsty                # repo name, pigsty by default
repo_address: pigsty             # external address to this repo (ip:port or url)
repo_rebuild: false              # force re-download packages
repo_remove: true                # remove existing upstream repo
repo_upstreams: [ ]              # where to download packages?
repo_packages: [ ]               # which packages to be included
repo_url_packages: [ ]           # extra packages from url

#-----------------------------------------------------------------
# INTERNAL FLAG
#-----------------------------------------------------------------
repo_exists: false # internal flag

#-----------------------------------------------------------------
# NGINX (REFERENCE)
#-----------------------------------------------------------------
nginx_enabled: true               # build local repo on this node
nginx_port: 80                    # repo listen address, must same as repo_address
nginx_home: /www                  # default repo home dir
...