---
#-----------------------------------------------------------------
# CA
#-----------------------------------------------------------------
ca_method: create                # create|copy|recreate
ca_subject: "/CN=root-ca"        # self-signed CA subject
ca_homedir: /ca                  # ca cert directory
ca_cert: ca.crt                  # ca public key/cert
ca_key: ca.key                   # ca private key
...