#!/usr/bin/env ansible-playbook
---
#==============================================================#
# Init a local yum repo powered by a local nginx web server
# all necessary rpm packages are downloaded to accelerate
# cluster initialization, or in case that target machine does
# not have internet access.
#
# RPM packages are downloaded to {{ nginx_home }}/{{ repo_name }}.
# And it will skip download if all packages already exists
#
# Local yum repo url:  http://{{ repo_address }}/{{ repo_name }}/
#==============================================================#


#--------------------------------------------------------------#
# 1. Pre Flight
#--------------------------------------------------------------#
# create repo directory and check cache existence
- name: Create local repo directory
  tags: repo_dir
  file: path={{ nginx_home }}/{{ repo_name }} state=directory mode=0755

#--------------------------------------------------------------#
# 2. Upstream repo
#--------------------------------------------------------------#
# install upstream repo to download packages
# upstream repo are only installed when download is necessary
- name: Install upstream repos
  tags: repo_upstream
  block:
    # if repo_remove = true, existing repos will be moved to backup dir
    - name: Backup & remove existing repos
      shell:
        warn: no
        cmd: |
          mkdir -p /etc/yum.repos.d/backup;
          mv -f /etc/yum.repos.d/*.repo /etc/yum.repos.d/backup/; true

    # add all upstream repos
    - name: Add required upstream repos
      yum_repository: "{{ item }}"
      with_items: "{{ repo_upstreams }}"


#--------------------------------------------------------------#
# 3. Prepare repo (if cache exists)
#--------------------------------------------------------------#
# a valid local yum repo is identified with existence of flag file:
# {{ nginx_home }}/{{ repo_name }}/repo_complete (/www/pigsty/repo_complete)

- name: Check local repo exists
  tags: repo_prepare
  block:
    # set repo_exists = true if local repo already exists
    - name: Check repo pkgs cache exists
      stat: path={{ nginx_home }}/{{ repo_name }}/repo_complete
      register: repo_cache
    - name: Set fact whether repo_exists
      connection: local
      set_fact:
        repo_exists: "{{ repo_cache.stat.exists }}"


# if repo exists, just create a local file repo definition
# so that we can install bootstrap pacakges from it
- name: Prepare repo
  tags: repo_prepare
  when: repo_exists
  block:
    # if local yum cache exists, use it instead
    - name: Move upstream repo to backup
      shell: mv -f /etc/yum.repos.d/*.repo /etc/yum.repos.d/backup/ || /bin/true

    # add local file repo
    - name: Add local file system repos
      yum_repository:
        name: "{{ repo_name }}-local"
        description: CentOS-$releasever - Updates - Aliyun Mirror
        baseurl: "file://{{ nginx_home }}/{{ repo_name }}"
        gpgcheck: no

    # this usually takes 1~2 minutes according to your network condition
    - name: Remake yum cache if not exists
      environment: "{{ proxy_env }}"
      shell: yum clean all; yum makecache; /bin/true


#--------------------------------------------------------------#
# 4. Bootstrap
#--------------------------------------------------------------#
# those packages are already installed during configure
# just make sure them exists
- name: Install repo bootstrap packages
  tags: repo_boot
  yum:
    name: "yum-utils,createrepo,nginx,wget,sshpass"
    state: latest

# launch nginx server for yum repo
- name: Bootstrap repo nginx server
  tags: repo_nginx
  block:
    # copy repo nginx config & content
    - name: Render repo nginx server files
      template: src={{ item.src }} dest={{ item.dest }} mode=0644
      with_items:
        - {src: nginx.conf.j2,    dest: /etc/nginx/nginx.conf}
        - {src: default.conf.j2,  dest: /etc/nginx/conf.d/default.conf}
        - {src: index.html.j2,    dest: "{{ nginx_home }}/index.html" }
        - {src: local.repo.j2,    dest: "{{ nginx_home }}/{{ repo_name }}.repo"}

    # nginx sometimes may not work if selinux is enabled
    - name: Disable selinux for repo server
      selinux: state=disabled

    # launch nginx with systemctl and wait for port 80 online
    - name: Launch repo nginx server
      systemd: name=nginx state=restarted enabled=yes daemon_reload=yes

    - name: Waits repo server online
      wait_for: host=127.0.0.1 port=80 state=started



#--------------------------------------------------------------#
# 5. Download
#--------------------------------------------------------------#
# if repo cache flag file missing, or force rebuild repo, then download repo packages
- name: Download local repo packages
  tags: repo_download
  when: not repo_exists
  block:

    # download packages from upstream yum repo
    - name: Download repo packages
      tags: repo_pkg
      environment: "{{ proxy_env }}"
      command:
        cmd: yum install --downloadonly --downloaddir={{ nginx_home }}/{{ repo_name }} {{ item }}
        chdir: "{{ nginx_home }}/{{ repo_name }}"
      with_items: "{{ repo_packages }}"

    # download packages directly via url
    - name: Download web url packages
      tags: repo_pkg_url
      environment: "{{ proxy_env }}"
      get_url: dest={{ nginx_home }}/{{ repo_name }}/{{ item | basename }} url={{ item }}
      with_items: "{{ repo_url_packages }}"

    # download rpm according to url
    - name: Download repo pkg dependencies
      tags: repo_pkg_deps
      environment: "{{ proxy_env }}"
      command:
        cmd: repotrack {{ item }}
        chdir: "{{ nginx_home }}/{{ repo_name }}"
      with_items: "{{ repo_packages }}"

    # create local yum repo
    - name: Create local repo
      tags: repo_create
      shell: |
        cd {{ nginx_home }}/{{ repo_name }}
        createrepo {{ nginx_home }}/{{ repo_name }}
        md5sum * > repo_complete || /bin/true

...