---
#------------------------------------------------------------------------------
# Setup DNS
#------------------------------------------------------------------------------
- name: Setup node dns records
  tags: node_dns
  block:
    # - name: Write local nodename to /etc/hosts
    #   when: nodename is defined and nodename != ''
    #   lineinfile: path=/etc/hosts line="127.0.0.1 {{ nodename }}"

    - name: Write static dns records to /etc/hosts
      when: node_etc_hosts_default is defined and node_etc_hosts_default|length > 0
      lineinfile: path=/etc/hosts line="{{ item }}"
      with_items: "{{ node_etc_hosts_default }}"

    - name: Write extra static dns records to /etc/hosts
      when: node_etc_hosts is defined and node_etc_hosts|length > 0
      lineinfile: path=/etc/hosts line="{{ item }}"
      with_items: "{{ node_etc_hosts }}"


#------------------------------------------------------------------------------
# Setup Resolver
#------------------------------------------------------------------------------
# add static nameserver to resolv (if node_dns_method != 'none')
- name: Setup node dns resolver
  tags: node_resolv
  when: node_dns_method is defined and node_dns_method != 'none'
  block:
    # add new nameservers to existing nameservers
    - name: Get old nameservers
      when: node_dns_method == 'add'
      shell: grep -E '^nameserver' /etc/resolv.conf  | grep -Eo '[0-9\.]+' | head -n3
      register: old_nameservers

    - name: Write tmp resolv file
      shell: echo -n "" > /etc/resolv.conf.tmp

    - name: Write resolv options
      shell: echo {{ item }} >> /etc/resolv.conf.tmp
      with_items: "{{ node_dns_options }}"

    - name: Write additional nameservers
      shell: echo "nameserver {{ item }}" >> /etc/resolv.conf.tmp
      with_items: "{{ node_dns_servers }}"

    - name: Append existing nameservers
      shell: echo "nameserver {{ item }}" >> /etc/resolv.conf.tmp
      with_items: "{{ old_nameservers.stdout_lines }}"
      when: node_dns_method == 'add' and item not in node_dns_servers

    - name: Swap resolv.conf
      shell: mv -f /etc/resolv.conf /etc/resolv.conf.backup; mv /etc/resolv.conf.tmp /etc/resolv.conf

...