---
#------------------------------------------------------------------------------
# Setup node repo
#------------------------------------------------------------------------------
- name: Install pigsty yum repo
  tags: node_repo
  block:
    # remove existing repos to backup dir
    - name: Backup existing repos
      when: node_repo_remove|bool
      shell:
        warn: no
        cmd: mkdir -p /etc/yum.repos.d/backup ; mv -f /etc/yum.repos.d/*.repo /etc/yum.repos.d/backup/; true

    # install public repo (default, use this if you have public internet access)
    - name: Install upstream repo
      when: node_repo_method == "public"
      yum_repository: "{{ item }}"
      with_items: "{{ repo_upstreams }}"

    # install local repo from url or file
    - name: Install local repo
      when: node_repo_method == "local"
      get_url:
        url: "{{ item }}"
        dest: /etc/yum.repos.d/{{ item | basename }}
      with_items: "{{ node_repo_local_urls }}"


#------------------------------------------------------------------------------
# Install packages directly from public internet
#------------------------------------------------------------------------------
- name: Install node packages directly
  tags: node_pkgs
  when: node_repo_method == 'public'
  block:
    # install common node packages
    - name: Install node basic packages
      environment: "{{ proxy_env | default({}) }}"
      yum: name={{ item }} disable_gpg_check=true
      with_items: "{{ node_packages_default }}"

    - name: Install node extra packages
      environment: "{{ proxy_env | default({}) }}"
      yum: name={{ item }} disable_gpg_check=true
      with_items: "{{ node_packages }}"

    - name: Install meta specific packages
      when: meta_node|bool
      environment: "{{ proxy_env | default({}) }}"
      yum: name={{ item }} disable_gpg_check=true
      with_items: "{{ node_packages_meta }}"


#------------------------------------------------------------------------------
# Install packages from local repo
#------------------------------------------------------------------------------
- name: Install node packages from loca repo
  tags: node_pkgs
  when: node_repo_method == 'local'
  block:
    # install common node packages
    - name: Install node basic packages
      yum: name={{ item }} disable_gpg_check=true
      with_items: "{{ node_packages_default }}"

    - name: Install node extra packages
      yum: name={{ item }} disable_gpg_check=true
      with_items: "{{ node_packages }}"

    - name: Install meta specific packages
      when: meta_node|bool
      yum: name={{ item }} disable_gpg_check=true
      with_items: "{{ node_packages_meta }}"


#------------------------------------------------------------------------------
# Install Python Packages with pip3
#------------------------------------------------------------------------------
- name: Install pip3 packages on meta node
  tags: [ node_pkgs, node_pip ]
  when: meta_node|bool and node_packages_meta_pip != ''
  ignore_errors: yes
  environment: "{{ proxy_env | default({}) }}"
  shell: |
    #!/bin/bash
    mkdir -p {{ nginx_home }}/{{ repo_name }}/python
    cd {{ nginx_home }}/{{ repo_name }}/python
    if [[ ! -f pip_downloaded ]]; then
        pip3 install --upgrade pip
        /usr/bin/pip3 download pip
        /usr/bin/pip3 download {{ node_packages_meta_pip }}
        touch pip_downloaded
    fi
    rm -rf pip_downloaded
    /usr/bin/pip3 install {{ nginx_home }}/{{ repo_name }}/python/pip* || true
    /usr/bin/pip3 install {{ nginx_home }}/{{ repo_name }}/python/* || true
    touch pip_downloaded

...
