---
#------------------------------------------------------------------------------
# Install
#------------------------------------------------------------------------------
- name: Install prometheus and alertmanager
  package: name={{ item }} state=present
  with_items:
    - prometheus2
    - alertmanager

#------------------------------------------------------------------------------
# Cleanup
#------------------------------------------------------------------------------
# remove existing prometheus (if required)
- import_tasks: cleanup.yml
  tags: prometheus_clean
  when: not prometheus_reload

#------------------------------------------------------------------------------
# Config
#------------------------------------------------------------------------------
# config prometheus & alertmanager
- import_tasks: config.yml
  tags: prometheus_config

#------------------------------------------------------------------------------
# Launch
#------------------------------------------------------------------------------
# launch prometheus
- import_tasks: launch.yml
  when: prometheus_enabled|bool
  tags: prometheus_launch

#------------------------------------------------------------------------------
# Reload
#------------------------------------------------------------------------------
# reload are required to load new rules/alert, not necessary for new targets
- import_tasks: reload.yml
  when: prometheus_enabled|bool
  tags: prometheus_reload

...


